### ISSUE TITLE
How to change port for some Server Modules?

### ISSUE THREAD

**Issue by AntoninHL** [qeeqbox/chameleon#4]
Hello,

first of all, many thanks for this really impressive work!

I want to change the listen port for SSH and I want to disable DNS Server.
How can I do that?
I tried to change ssh_server.py, or to move dns_server in another location, but failed

Many thanks for your help

**Comment by giga-a** [comment]
Hey @AntoninHL!, I will make some changes in the next week or so (This will allow users to change a port or disable a server)

**Comment by giga-a** [comment]
@AntoninHL I have added some changes that allow you to do that

Check out the [configuration file](https://github.com/qeeqbox/chameleon/blob/master/config.json)

That file will have an entry named honeypots, you can choose what honeypots to keep, disable, or change a port

```json
{
	"logs":"db",
	"logs_location":"",
	"host":"chameleon_postgres",
	"port":9999,
	"username":"changeme027a088931d22",
	"password":"changeme0f40773877963",
	"db":"chameleon",
	"interface":"eth0",
	"honeypots":"ftp:21,ssh:22,telnet:23,smtp:25,dns:53,http:80,pop3:110,imap:143,https:443,postgres:5432,smb:445,socks5:1080,mysql:3306,vnc:5900,redis:6379,httpproxy:8080"
}
```

**Comment by AntoninHL** [comment]
Thanks @giga-a 

But seems that config.json is not taken into account by `./run.sh auto_configuration` command...

config.json file:
![image](https://user-images.githubusercontent.com/50768/121889377-74a85f00-cd19-11eb-9b1d-b67623523cd4.png)

result:
![image](https://user-images.githubusercontent.com/50768/121889438-87bb2f00-cd19-11eb-8f6b-2ef052184c7b.png)

I don't really understand why...

**Comment by giga-a** [comment]
Hey @AntoninHL 

Thanks for getting back to me!

> I don't really understand why...

The `./run.sh auto_configure` command uses different configurations file (`docker-compose-dev.yml`). It publishes any port defined in the `ports` element. 

If your host is running ssh on port 22 and `docker-compose-dev.yml` has `'22:22'` in the `ports` element, it will show something like

`ERROR: for honeypots  Cannot start service honeypots: driver failed programming external connectivity on endpoint chameleon_honeypots_1 (34a10704281a3b9ac7cfd4801b9230493b89223b0e2818e2fe953af4578ccb27): Error starting userland proxy: listen tcp4 0.0.0.0:22: bind: address already in use`

If your host is running Apache on port 80 and `docker-compose-dev.yml` has `'80:80'` in the `ports` element, it will show something like

`ERROR: for honeypots  Cannot start service honeypots: driver failed programming external connectivity on endpoint chameleon_honeypots_1 (4cd76dcc58a75d26ab268c01606839ecc380b629f39706032607598969f85a14): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use`

And so on,

**To fix the issue**, remove the service port from the `ports` element in `docker-compose-dev.yml`

Instead of this
```
    ports:
      - '21:21'
      - '22:22'
      - '23:23'
      - '25:25'
      - '80:80'
      - '110:110'
      - '143:143'
      - '443:443'
      - '445:445'
      - '1080:1080'
      - '1433:1433'
      - '3306:3306'
      - '3389:3389'
      - '5900:5900'
      - '6379:6379'
      - '8080:8080'
      - '9200:9200'

```

I'm assuming you want only ftp, telnet and smtp
```
    ports:
      - '21:21'
      - '23:23'
      - '25:25'

```

There are other options to fix the same issue but they may take more steps:
- Disable the service on your host
- Change the host service port on your host

Please let me know if that works for you or not?

P.S. I will push an update by the end of this week that handles that automatically based on the `config.json`

**Comment by AntoninHL** [comment]
Hi @giga-a 

Awesome.
Understand now.

Another "small" question: is it possible to change the network interface?
For example, instead of eth0, specify ens3 or eno1.

Once again, I changed config.json, but no effect.

Many thanks.

**Comment by giga-a** [comment]
@AntoninHL you are very welcome!

I'm pretty sure that you can change the interface to anything you want - I will take a look and get back to you tomorrow morning :)

**Comment by giga-a** [comment]
Hey @AntoninHL, sorry for the delay - I had to push a new update to both honeypots and chameleon. 

> For example, instead of eth0, specify ens3 or eno1.
> Once again, I changed config.json, but no effect.

The network interface is used for `QSniffer` module, it's for monitoring the network traffic for loose creds etc.. This `QSniffer` module can be disabled if you are running into issues with it (I will add an option to disable it). My only guess that you are probably changing that network interface to a local network interface instead of the ones listed in the docker container. I could be wrong though, but I believe it will be easier to resolve after the new update.

- The new update should handle your ports issue. When you deploy Chameleon with `./run.sh deploy` it will adjust a copy of `docker-compose-dep.yml` with the ports listed in `config.json`. If you have ftp honeypot in your `config.json`, then ftp honeypot port will be published only and so on
- If you pass `ens3` and `ens3` does not it exists, then there will an error in your terminal + all available interfaces. 
- I added more honeypots, changed some Grafana settings and added [syslog logging](https://github.com/qeeqbox/chameleon/issues/5)
- There is no more `./run.sh auto_configre` and `./run.sh auto_configre_test` -> I replaced them with `./run.sh test` and `./run.sh deploy`

<img src="https://raw.githubusercontent.com/qeeqbox/chameleon/master/readme/intro.gif" style="max-width:768px"/>

Please let me know if you are running into any issues with the new update so I fix it

Cheers 🍻
